//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpensesmanagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Expens
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Expens()
        {
            this.Supervisors = new HashSet<Supervisor>();
        }
    
        public int ReceiptNo { get; set; }
        public Nullable<System.DateTime> Receiptdate { get; set; }
        public Nullable<int> Receiptamount { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public string StatusofReceipt { get; set; }
        public string UploadReceipt { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Status Status { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Supervisor> Supervisors { get; set; }
    }
}
